//
// Copyright © Agulhas Labs
//

import Foundation

/// Renders a `similar` answer: one line per hit, an evidence line under it, and a caveat that says what a ranking of written names can and cannot mean.
///
/// No source bodies. The answer exists to be read before a helper is written, and what that decision needs is where the nearest existing shapes are and why they ranked — three or four lines. Serving bodies would make the cheap question cost what reading the files costs, which is the thing it replaces; `digest Type.member` is one call away and is named in the caveat for exactly that.
struct SimilarRenderer {
    static func render(answer: SimilarAnswer) -> String {
        switch answer.outcome {
        case let .ranked(subject, hits, above):
            ranked(answer: answer, subject: subject, hits: hits, above: above)
        case let .thin(subject):
            thin(subject: subject)
        case let .ambiguous(candidates):
            ambiguous(answer: answer, candidates: candidates)
        case .unresolved:
            unresolved(answer: answer)
        }
    }

    /// What the floor is a floor on, said where the count is, because the number beside each hit is not the number that admitted it: the list is gated on rarity-weighted callee overlap alone and then ordered by all three terms.
    static var floorPhrase: String {
        floorPhrase(at: SimilarityScore.calleeFloor)
    }

    /// The same phrase at another floor, so `dupes` states its own number in the words `similar` uses for this one.
    static func floorPhrase(at floor: Double) -> String {
        "\(formatted(floor)) shared-callee overlap or better (rarity-weighted; the score also weighs control flow and written types)"
    }

    /// What the answer does and does not promise.
    ///
    /// Three things, all load-bearing. It matches **written names**, so two unrelated types' `save` are one name here and a hit is a lead rather than a fact — the same limit `search`'s own caveat states, for the same reason. It is a **lower bound**: a helper built on a different call, or generated by a macro, is shape this scan cannot see, so an empty list means nothing close by callee or shape, never that there is nothing to reuse. And it is a working-tree read, so nothing in it can be stale.
    static var caveat: String {
        "syntactic shape match on written names over the working tree — never stale; a hit is a lead to confirm with "
            + "digest Type.member, and the list is a lower bound, never a verdict: nothing above the floor means nothing "
            + "close by callee or shape, not that there is nothing to reuse."
    }

    private static func ranked(answer: SimilarAnswer, subject: DeclarationFingerprint, hits: [SimilarHit], above: Int) -> String {
        var lines = [heading(subject: subject)]
        guard !hits.isEmpty else {
            lines.append("no declaration reached \(floorPhrase) — of \(answer.census.candidates) with a body in \(answer.census.filesScanned) file(s)")
            lines.append(caveat)
            return lines.joined(separator: "\n")
        }
        let listed = hits.count == above ? "" : ", closest \(hits.count) listed"
        lines.append("\(above) declaration(s) at \(floorPhrase)\(listed) — of \(answer.census.candidates) with a body in \(answer.census.filesScanned) file(s)")
        lines.append(caveat)
        lines.append("ordered by the full score, closest first; the number beside each hit is its shared-callee overlap, the one the floor is on, so it need not fall down the list.")
        lines.append("")
        for hit in hits {
            // The floor is on callee overlap, so that is the number a reader can check against `floorPhrase` —
            // the hit is still ranked and ordered by the composite score.
            lines.append("  \(formatted(hit.calleeOverlap))  " + located(hit.fingerprint))
            if !hit.sharedCallees.isEmpty {
                lines.append("        shares: " + hit.sharedCallees.joined(separator: ", "))
            }
        }
        return lines.joined(separator: "\n")
    }

    /// A target with almost no calls in it is answered with the query that *can* find its neighbours, not with a ranking built on one piece of evidence.
    private static func thin(subject: DeclarationFingerprint) -> String {
        let count = subject.callees.count
        var lines = [heading(subject: subject)]
        lines.append("too thin to compare: \(count) call(s) in its body, and this ranks by shared callees — \(SimilarityScore.minimumCallees) is the floor, below which every ordering is noise.")
        let recipe = subject.callees.sorted().first.map { "kind:func calls:\($0)" } ?? "kind:func calls:<the call it cannot do without>"
        lines.append("ask by the call a helper cannot do without instead: search '\(recipe)' — one query per candidate callee, since terms are ANDed and there is no OR.")
        return lines.joined(separator: "\n")
    }

    private static func ambiguous(answer: SimilarAnswer, candidates: [DeclarationFingerprint]) -> String {
        let listed = Array(candidates.prefix(SimilarityScore.resultCap))
        var lines = ["similar \(answer.target) — \(candidates.count) declaration(s) answer to it; name one"]
        lines.append(contentsOf: listed.map { "  " + located($0) })
        if candidates.count > listed.count {
            lines.append("… truncated: \(candidates.count - listed.count) more")
        }
        return lines.joined(separator: "\n")
    }

    private static func unresolved(answer: SimilarAnswer) -> String {
        """
        similar \(answer.target) — no declaration with a body answers to it
        similar compares bodies, so its candidates are funcs, inits, subscripts and computed vars that have one: a protocol requirement, a stored property and a type itself have none. Scanned \(answer.census.filesScanned) file(s), \(answer.census.candidates) declaration(s) with a body.
        where \(answer.target) locates it if it exists at all, and digest names the labeled form a member target needs.
        """
    }

    /// What the target resolved to.
    ///
    /// The signature is left off here and kept on the hits: what a reader needs of the subject is which declaration was taken, and they wrote the name themselves — where a hit is something they have not seen.
    private static func heading(subject: DeclarationFingerprint) -> String {
        let declaration = subject.declaration
        return "similar \(declaration.qualifiedName) — \(declaration.path):\(declaration.line)-\(declaration.endLine)"
    }

    /// The locator line a hit and a subject share: where it is, what it is called, how it is written.
    static func located(_ fingerprint: DeclarationFingerprint) -> String {
        let declaration = fingerprint.declaration
        return "\(declaration.path):\(declaration.line)-\(declaration.endLine)  \(declaration.qualifiedName) — \(declaration.signature)"
    }

    /// Two decimals, so the floor in the header and the scores under it are the same kind of number.
    static func formatted(_ score: Double) -> String {
        String(format: "%.2f", score)
    }
}
